### ISSUE TITLE
Try cmd /s /c instead of the temporary batch file

### ISSUE THREAD

**Issue by Artoria2e5** [mklement0/Native#2]
`cmd.exe` does have a simpler mode for passing in command-line stuff: use `/s` and put a pair of double quotes over whatever is in `/c` as the end of the cmdline. The quote would be simply stripped and the contents used.

**Comment by mklement0** [comment]
Thanks for the suggestion, but I think it is ultimately preferable to use batch-file syntax than command-line syntax.

E.g., I want the following to work, which wouldn't work with `cmd /s /c`:

```powershell
PS> ins 'for %%i in (1 2 3) do echo %%i'`
1
2
3
```

```powershell
PS> ins 'echo The value of %%CD%% is %CD%.'
The value of %CD% is C:\Users\jdoe
```

**Comment by mklement0** [comment]
The second reason I'm using a temporary batch file is that it enables passing arguments to the command, i.e. to treat it as a an ad hoc batch file, just like you can analogously on Unix:

```powershell
PS> ins 'ver & echo %1' foo

Microsoft Windows [Version 10.0.18363.1016]
foo
```
